// src/lib/books.js — Bible book metadata for API.Bible NIV
// Book IDs follow API.Bible's format for NIV (06125adad2d5898a-01)

export const BIBLE_BOOKS = [
  // Old Testament
  { id: 'GEN', label: 'Genesis', chapters: 50 },
  { id: 'EXO', label: 'Exodus', chapters: 40 },
  { id: 'LEV', label: 'Leviticus', chapters: 27 },
  { id: 'NUM', label: 'Numbers', chapters: 36 },
  { id: 'DEU', label: 'Deuteronomy', chapters: 34 },
  { id: 'JOS', label: 'Joshua', chapters: 24 },
  { id: 'JDG', label: 'Judges', chapters: 21 },
  { id: 'RUT', label: 'Ruth', chapters: 4 },
  { id: '1SA', label: '1 Samuel', chapters: 31 },
  { id: '2SA', label: '2 Samuel', chapters: 24 },
  { id: '1KI', label: '1 Kings', chapters: 22 },
  { id: '2KI', label: '2 Kings', chapters: 25 },
  { id: '1CH', label: '1 Chronicles', chapters: 29 },
  { id: '2CH', label: '2 Chronicles', chapters: 36 },
  { id: 'EZR', label: 'Ezra', chapters: 10 },
  { id: 'NEH', label: 'Nehemiah', chapters: 13 },
  { id: 'EST', label: 'Esther', chapters: 10 },
  { id: 'JOB', label: 'Job', chapters: 42 },
  { id: 'PSA', label: 'Psalms', chapters: 150 },
  { id: 'PRO', label: 'Proverbs', chapters: 31 },
  { id: 'ECC', label: 'Ecclesiastes', chapters: 12 },
  { id: 'SNG', label: 'Song of Solomon', chapters: 8 },
  { id: 'ISA', label: 'Isaiah', chapters: 66 },
  { id: 'JER', label: 'Jeremiah', chapters: 52 },
  { id: 'LAM', label: 'Lamentations', chapters: 5 },
  { id: 'EZK', label: 'Ezekiel', chapters: 48 },
  { id: 'DAN', label: 'Daniel', chapters: 12 },
  { id: 'HOS', label: 'Hosea', chapters: 14 },
  { id: 'JOL', label: 'Joel', chapters: 3 },
  { id: 'AMO', label: 'Amos', chapters: 9 },
  { id: 'OBA', label: 'Obadiah', chapters: 1 },
  { id: 'JON', label: 'Jonah', chapters: 4 },
  { id: 'MIC', label: 'Micah', chapters: 7 },
  { id: 'NAM', label: 'Nahum', chapters: 3 },
  { id: 'HAB', label: 'Habakkuk', chapters: 3 },
  { id: 'ZEP', label: 'Zephaniah', chapters: 3 },
  { id: 'HAG', label: 'Haggai', chapters: 2 },
  { id: 'ZEC', label: 'Zechariah', chapters: 14 },
  { id: 'MAL', label: 'Malachi', chapters: 4 },
  // New Testament
  { id: 'MAT', label: 'Matthew', chapters: 28 },
  { id: 'MRK', label: 'Mark', chapters: 16 },
  { id: 'LUK', label: 'Luke', chapters: 24 },
  { id: 'JHN', label: 'John', chapters: 21 },
  { id: 'ACT', label: 'Acts', chapters: 28 },
  { id: 'ROM', label: 'Romans', chapters: 16 },
  { id: '1CO', label: '1 Corinthians', chapters: 16 },
  { id: '2CO', label: '2 Corinthians', chapters: 13 },
  { id: 'GAL', label: 'Galatians', chapters: 6 },
  { id: 'EPH', label: 'Ephesians', chapters: 6 },
  { id: 'PHP', label: 'Philippians', chapters: 4 },
  { id: 'COL', label: 'Colossians', chapters: 4 },
  { id: '1TH', label: '1 Thessalonians', chapters: 5 },
  { id: '2TH', label: '2 Thessalonians', chapters: 3 },
  { id: '1TI', label: '1 Timothy', chapters: 6 },
  { id: '2TI', label: '2 Timothy', chapters: 4 },
  { id: 'TIT', label: 'Titus', chapters: 3 },
  { id: 'PHM', label: 'Philemon', chapters: 1 },
  { id: 'HEB', label: 'Hebrews', chapters: 13 },
  { id: 'JAS', label: 'James', chapters: 5 },
  { id: '1PE', label: '1 Peter', chapters: 5 },
  { id: '2PE', label: '2 Peter', chapters: 3 },
  { id: '1JN', label: '1 John', chapters: 5 },
  { id: '2JN', label: '2 John', chapters: 1 },
  { id: '3JN', label: '3 John', chapters: 1 },
  { id: 'JUD', label: 'Jude', chapters: 1 },
  { id: 'REV', label: 'Revelation', chapters: 22 },
];

export function getBookById(id) {
  return BIBLE_BOOKS.find(b => b.id === id);
}
